### PR TITLE
[WIP] More updates

### PR DESCRIPTION
**Pull request by Prashank25**
### Don't merge this yet.

More updates, the usual stuff.
Install script updated.
More php7 compatibility fixes.
Added a common exception handler (with email reports for PDOException) - `/inc/exceptions/Handler.php`
screenshot-dolphinpro dev 2016-05-19 23-40-49

I have updated the BxDolDb class again. I saw @AntonLV updated this class to include some try...catch block to suppress the exceptions and reporting errors with the local methods, I have overwrote it. I would suggest taking a look at the BxDolDb.php and exceptions/Handler.php files. It seems better to me to let the exception bubble up the stack and let the handler handle it, in header.inc.php file is a new boolean option `$site['fullError']` to hide the full error for production environments.

To-Do:
> Update orca forum
> Update everything to psr-2 standard (comment requested)
> Run a php 7 compatibility check
> Migrate the database over from MyISAM to InnoDb (comment requested)
> Fix whatever bugs appear

I am looking into running some tests with 3rd party modules, they still only need to update `__construct` and `mysql_*` functions in theory.

Looking for any comments. Thank you.

### CODE REVIEW

**Comment by AlexTr** [comment]
Thank you @Prashank25 it's very valuable contribution, but some fixes are needed. 
It looks like your exception handler is better approach, but some tweaks are needed.
1) It was some more changes in BxDolDb class, merge all previous changes except try...catch blocks
2) Move Handler to classes folder and name it BxDolExceptionsHandler
3) Comments in Handler class state that methods throw exceptions but it looks like it isn't
4) Respect previous settings for the following settigs:
```
//define('DB_FULL_VISUAL_PROCESSING', true);
//define('DB_FULL_DEBUG_MODE', true);
//define('DB_DO_EMAIL_ERROR_REPORT', true);
```
Just move it to header.inc.php, since now it's impossible to disable email reports at all
5) Use BxDolTrail prefix for traits, so we can implement auto-loading later

**Comment by AlexTr** [comment]
6) Also you've removed "reconnect" feature from BxDolDb::res function, it's critical to have reconnect functionality. Maybe it's build'in into PDO already ?

**Comment by Prashank25** [comment]
@AlexTr 

1. Hmm... are you talking about [this commit](https://github.com/boonex/dolphin.pro/commit/3229e50a111eddc0dcd7d1874090f89192b88a9d)? I don't see what else that needs to be merged? Am I looking at the wrong commit or something?

3. Where?

6. Have you checked BxDolDb class from the latest commit at line [#168](https://github.com/Prashank25/dolphin.pro/blob/deprecated_stuff/inc/classes/BxDolDb.php#L168)
It does try to reconnect and run the query again in specific case of "[gone away](http://dev.mysql.com/doc/refman/5.7/en/gone-away.html)". I haven't tested it enough tho, i will look into that.

**Comment by AlexTr** [comment]
@Prashank25 

1) We changed BxDolDb to behave it the same way as in Trident, so it will make code from both versions compatible. You've mentioned that you've overwrote the file, so I afraid that out last changes are lost. Also you've said that you've removed only try..catch blocks, but there are many more changed, including methods repositioning, which makes merging very difficult. 
So could you assure that our changes aren't lost and you didn't overwrite it ?
Also please make sure that the code behave the same way with the same parameters in Trident and Dolphin. 

3) Sorry, I didn't checked it properly, it just a type of parameter.

6) Sorry, you are right, reconnect functionality is there. But I've noticed just one thing now - $bReplaying is false by default, so it shouldn't reconnect, but it makes the opposite. It maybe better to make it true by default and do reconnect in case of server gone away.

Thank you.

**Comment by Prashank25** [comment]
1) Can you merge whatever you want to upstream, from trident or this pull request? I don't seem to understand the requirement of code compatibility between trident and dolphin pro.

3) at line 166 is this inside the catch statement
`
if (!$bReplaying && (stripos($e->getMessage(), 'gone away') !== false)) {
`
So it should run by default, if it gets disconnected, And not if its replaying the call after trying to reconnect cuz we don't want an infinite recursion. I don't see any logic errors here?

**Comment by AlexTr** [comment]
1) we've just merged it, but you've said that you overwrote this file, so I'm trying to understand if you got all recent changes and applied yours, or overwrote all these changes ?

2) `$bReplaying` - for me it is like "repeat", but looking at your code the condition is inverted, so for me it's ore logical to change it to the following:
```php
 if ($bReplaying && (stripos($e->getMessage(), 'gone away') !== false)) { 
```

**Pull request merged**
