### PR TITLE
Sites: STW settings title changes; searchKeyword: changed parts selector from checkbox to buttons

### PR DESCRIPTION
**Pull request by apachler**
- Sites: STW settings title changes
- searchKeyword: changed parts selector from checkbox to buttons

### CODE REVIEW

**Comment by apachler** [comment]
Sorry Alex, i have no chance to split my commits into different pull requests

**Comment by AlexTr** [comment]
@apachler 

I've merged STW settings titles -  #248

What is the point to change checkboxes to buttons on search page ?

**Comment by apachler** [comment]
Because of the design of the checkboxes. If you have a lot of modules installed, the checkboxes will generate a hugh list that need a lot of vertical space. Many of my customers have ask for a fix and therefore i have developed that solution.
Also the checkboxes are not looking nicely and make some problem on mobile devices.

**Comment by AlexTr** [comment]
Thank you @apachler the feature was merged - #251

**Pull request closed without merging**
