### PR TITLE
Dragging it to 2016

### PR DESCRIPTION
**Pull request by Prashank25**
There are bazillion updates and fixes to minor notices and warnings. I tried to replace all depreciated code except the mysql (maybe later). This will require modules to update minor things like using "__construct" instead of php 4 style, so maybe 7.4 release? I have replaced all preg_replace call with "/e"  modifier ([issue](http://php.net/manual/en/reference.pcre.pattern.modifiers.php#reference.pcre.pattern.modifiers.eval)) with preg_replace_callback (check BxDolTemplate).

In theory, if you can install mysql extension on php7 [(how to)](https://ckon.wordpress.com/2015/08/06/put-mysql-functions-back-into-php-7/) then this should run fine. With notices and strict warnings disabled of course. There are way too many notices to deal with, so I admitted defeat :cry:

Edit: Forgot to mention, it drops support for php 5.3, min 5.4 required.

### CODE REVIEW

**Comment by AlexTr** [comment]
Thank you @Prashank25 for such great efforts!

**Comment by AlexTr** [comment]
It's definitely for 7.4 milestone

**Comment by Prashank25** [comment]
some php 7 benchmark
https://www.boonex.com/forums/topic/Dolphin-benchmark-on-php-7.htm

**Comment by apachler** [comment]
Very nice Prashank!

**Comment by Prashank25** [comment]
@AlexTr 

Check out the BxDolDb class, I replaced mysql with PDO. I tired to maintain backward compatibility by not changing the methods signature, so all old code which used the methods on this class should work fine without realising that underline implementation has changed.

Except for cases where they used mysql functions directly.
like these cases, ofc

`
while ($row = mysql_fetch_assoc($stmt)) {
`

will have to be replaced with

`
while ($row = $stmt->fetch()) {
`

> I used regex in my editor (PHPStorm) to search and replace
> mysql_fetch_assoc\\((.*?)\\)
> $1->fetch()

This is very much a work in progress, a lot of things still need replacements but it runs as is.
Would you mind creating a separate branch for whatever version release Boonex wants this in (if at all), and merge this?

**Comment by AlexTr** [comment]
Thank you @Prashank25 !

**Comment by AlexTr** [comment]
> Would you mind creating a separate branch for whatever version release Boonex wants this in (if at all), and merge this?
Yes, we've created 7.3 branch and merged all these changes.

**Pull request merged**
