### PR TITLE
EVO service menu ignores admin settings for visitors

### PR DESCRIPTION
**Pull request by toxalot**
The service menu is hard-coded for visitors and always makes the Join tab active even if Join item is not an active menu item.

### CODE REVIEW

**Comment by AlexTr** [comment]
Thank you @toxalot 
I've noticed the problem with LoginOnly popup, if LoginOnly popup is opened first, then if you close this popup and tries to open regular login or join popup then the same LoginOnly popup is opened. Probably this is because they are using the same id.

**Comment by toxalot** [comment]
@AlexTr Yes, the popup is loaded on first open and then visibility is just toggled on subsequent clicks. I noticed that as well, but didn't consider it an issue that would arise in real usage. Why would anyone use LoginOnly and something else at the same time? I would consider that issue a `wontfix` since LoginOnly is designed to be used alone. Would you agree?

I also just wanted to mention that since Join is the only active visitor item by default, the default behavior remains unchanged.

**Comment by AlexTr** [comment]
If LoginOnly is used alone, then it is not an issue, so LoginOnly popup should be used only when join is disabled at all.

**Comment by toxalot** [comment]
Not sure what you are saying. Do you think code should be added to check whether or not Join is active? Or can we just leave this up to the admin to use the feature 'correctly'?

**Comment by AlexTr** [comment]
Yes, it should it up to admin to use it 'correctly'...

**Pull request merged**
