### PR TITLE
unified sites unit layout; WMap lat&lon support; singular title correction in groups WMap intergration; changed WMap sorting to pull newest entries first

### PR DESCRIPTION
**Pull request by apachler**
- Sites: changed the layout of sites unit to fit those of groups and events; also there was a problem with the sites unit in responsive view
- WMap: added support for latitude and longitude from part in WorldMap module
- Groups: wrong singular title for WMap integration of groups
- WMap: changed sorting to pull newest entries first

### CODE REVIEW

**Comment by apachler** [comment]
added support for latitude and longitude from part in WorldMap module

**Comment by apachler** [comment]
fixed wrong singular title for WMap integration of groups

**Comment by AlexTr** [comment]
Thank you @apachler for the commits. 
Please could you describe the point to add latitude/longitude fields ? actually world map module has separate table with lat/lng fields, I see no reason to make these fields external.

**Comment by apachler** [comment]
If a 3rd-Party module is using only lat/lng position data and NO address data there is no integration into WMap module available. So i did some minor changes that a 3rd-Party module can pass the lat/lng information to WMap. With this changes a 3rd-Party module can benefit from the WMap module even if it is not using addresses at all.

**Comment by AlexTr** [comment]
Ok, see the point - good example is EXIF data of an image! Request was merged!

Please could you make different pull request for different fixes/additions next time ?

Thank you, @apachler

**Comment by apachler** [comment]
Tried to create different pull requests but was not able to do it, sorry ... any hints?

**Comment by AlexTr** [comment]
I would suggest to make pull request after some feature/bug fix is completed, it's ok to have multiple commits in one pull request, but they should be related to the one problem/bugfix/enhancement.

Thank you for your contribution!

**Comment by apachler** [comment]
yes but this was not working for me ...

I commited a change to my fork, after that i created a pull request ... so for so good.
The i made another commit to my fork and that commit is automatically added to the
extisting pull request. No chance for me to create another pull request because i
always get redirected to the already existing one.

**Comment by AlexTr** [comment]
Please try to make pull request after each commit, or after series of commits related to each other and one issue/purpose.

Also it would be great if you could mention issue # number in the commit note.

Thank you for your contribution!

**Pull request merged**
