### PR TITLE
Full Width column/Row for page builder.

### PR DESCRIPTION
**Pull request by Prashank25**
Hello,
I added Full width column/Row to page builder.
[forum discussion](https://www.boonex.com/forums/topic/Looking-for-feedback-on-new-Full-Width-Column-Rows.htm)

Up to you to decide. Peace!

### CODE REVIEW

**Comment by notsenornathan** [comment]
+1 This would be an awesome addition to Dolphin.

**Comment by apachler** [comment]
+1 Yes, sir!! Thanks Prashank25

**Comment by yanivz** [comment]
+1

**Comment by AlexTr** [comment]
@Prashank25 please could you test it in UNI/ALT template ? it looks like it works in EVO template only

**Comment by AlexTr** [comment]
Thank you @Prashank25

**Pull request merged**
